#!/bin/bash
# build-safari.sh — Concatenate dependencies + background.js into a single bundle
# for Safari's service worker (which cannot reliably importScripts or use "scripts" array).
#
# Usage: cd "Safari extention" && bash build-safari.sh
#
# After running, copy the output to the Xcode Resources folder:
#   cp background-bundle.js "tablicate/tablicate Extension/Resources/background-bundle.js"

set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"

OUT="$DIR/background-bundle.js"

{
cat <<'HEADER'
// ============================================================================
// Tablicate Safari Extension — Background Bundle
// Auto-generated by build-safari.sh — do NOT edit directly.
// Edit the source files then re-run: bash build-safari.sh
// ============================================================================

// --- Browser polyfill ---
if (typeof globalThis.chrome === 'undefined' && typeof globalThis.browser !== 'undefined') {
    globalThis.chrome = globalThis.browser;
}
// Safari defines both chrome and browser, but may only expose certain APIs
// (like bookmarks) on browser. Merge missing namespaces onto chrome.
if (typeof globalThis.browser !== 'undefined' && typeof globalThis.chrome !== 'undefined') {
    for (const key of Object.keys(globalThis.browser)) {
        if (!globalThis.chrome[key]) {
            globalThis.chrome[key] = globalThis.browser[key];
        }
    }
}

// --- tweetnacl.min.js (embedded) ---
HEADER

cat "$DIR/lib/tweetnacl.min.js"
printf '\n\n'

cat <<'SHIM'
// --- nacl global shim ---
if (typeof self.nacl === 'undefined') {
    if (typeof module !== 'undefined' && module.exports && module.exports.secretbox) {
        self.nacl = module.exports;
    }
}
if (typeof nacl === 'undefined' && typeof self.nacl !== 'undefined') {
    /* eslint-disable no-var */
    var nacl = self.nacl;
}

// --- native-bridge.js (embedded) ---
SHIM

cat "$DIR/native-bridge.js"
printf '\n\n'

echo '// --- background.js (main logic — everything below this line) ---'

# Skip the first ~30 lines of background.js (browser polyfill + importScripts block).
# We only need the actual logic, starting from the Supabase section.
# Find the line number of the separator before "Supabase" and print from there.
START_LINE=$(grep -n 'Supabase Auth helpers' "$DIR/background.js" | head -1 | cut -d: -f1)
START_LINE=$((START_LINE - 1))  # include the separator line above it
tail -n "+$START_LINE" "$DIR/background.js"

} > "$OUT"

echo "✅ Built $OUT ($(wc -l < "$OUT") lines)"
